title: BonkersBricks
email: bonkersbricks@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Sharing my LEGO collection and creating instructions for custom creations!

# social links
instagram_username: bonkersbricks # DO NOT include the @ character, or else the build will fail!
twitter_username: bonkersbricks # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
